import exception
import fib

print(exception.greet('Alex'))
print(fib.fib(5))